### ISSUE TITLE
Баг с приватом (или фича?)

### ISSUE THREAD

**Issue by Leon-RUGDPS** [Rumaruka/Industrial-Magic---Crossover#12]
Чужой человек не имеющий доступа к региону может крутить механизмы ключом.
 (Если что-то не понятно **LEON#7451**)

**Comment by Rumaruka** [comment]
Причем тут приваты и мой мод?

**Comment by Leon-RUGDPS** [comment]
То есть это нормально что рандомный чел может перекрутить весь дом?

**Comment by Rumaruka** [comment]
Это надо админам вносить список , я не трогал привата вообще

**Comment by Leon-RUGDPS** [comment]
Разве на это не мод на приваты ?

**Comment by Rumaruka** [comment]
Нет

**Comment by Leon-RUGDPS** [comment]
Окей, тема закрыта.
