### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by TheRandomLabs** [Rumaruka/Industrial-Magic---Crossover#13]
[Here](https://github.com/Rumaruka/Industrial-Magic---Crossover/blob/6cd58b8acbe1d7fe57459d9c0dfc21680a0602a2/java/com/rumaruka/emt/command/CommandOutput.java#L59), the `compareTo` method calls itself, causing a `StackOverflowError`.

**Comment by Rumaruka** [comment]
I reboot windows and lost all my projects

**Comment by TheRandomLabs** [comment]
Can you not simply `git clone` this repository?

**Comment by Rumaruka** [comment]
I don't have time , later maybe

**Comment by Rumaruka** [comment]
Fixet
