### ISSUE TITLE
Thaumonomicon entries problem

### ISSUE THREAD

**Issue by xdanxlei** [Rumaruka/Industrial-Magic---Crossover#14]
I feel like the image should speak for itself
![Screenshot_25](https://user-images.githubusercontent.com/55701145/73669169-50f5f300-46a7-11ea-8a37-fc41c0ac6cdf.png)
I didn't do anything special. The only other mods I have are Thaum, Baubles and Industrial.

**Comment by Rumaruka** [comment]
I don't write lore about this, it's Don't bug ))
Maybe I continued develop this mod .... Maybe

**Comment by xdanxlei** [comment]
Ah! That explains it.

Thank you!
