### ISSUE TITLE
Sorry to post here, but didn't want to post on curseforge.

### ISSUE THREAD

**Issue by Trinsdar** [Rumaruka/Industrial-Magic---Crossover#15]
Do you know of any way I can contact the dev of the classic fork of this? name's weissmoon, was just wondering since his mod is sorta a fork of this, and I thought maybe you'de already talked to him on discrod or somewhere like that. if you don't know I'll just close this.
this is the mod by the way if you're curious: https://www.curseforge.com/minecraft/mc-mods/electro-magic-tools-ic2-classic

Also didn't you have a discord or something before? I could've swore i was in it till sometime this year.

**Comment by Rumaruka** [comment]
I don't know. I don't have contact this him. Sorry
