### ISSUE TITLE
Излишне высокая скорость перемещения в воздухе при экипированных вариантах ботинок путешественника из аддона.

### ISSUE THREAD

**Issue by KipoLord1** [Rumaruka/Industrial-Magic---Crossover#18]
Доброго времени суток, Владимир.
Проблема, собственно, описана в заголовке, прилагаю вот видео ещё.

https://user-images.githubusercontent.com/76908401/103493085-1796ac00-4e51-11eb-99ae-b6bebc80db0c.mp4

Из предложений: если это возможно, то вынести настройку, которая отвечает за скорость движения в воздухе, в файл конфигурации

**Comment by Rumaruka** [comment]
@KipoLord1 После огромного перерыва возвращаюсь к моду, ждите фикса и баланса предметов

**Comment by Rumaruka** [comment]
Скорость нефрнута у всех ботинков!
