### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by bigenergy** [Rumaruka/Industrial-Magic---Crossover#19]
Из версии в версию вы используете клиентский метод на стороне сервера, исправьте пожалуйста.
https://pastebin.com/mMkxkrTJ

**Comment by Rumaruka** [comment]
@bigenergy После огромного перерыва возвращаюсь к моду, ждите фикса и баланса предметов

**Comment by Rumaruka** [comment]
@bigenergy Это не шутка, действительно готовлюсь к полной переписки проекта, так что попытаюсь сделать так, чтобы серверу было лучше. 
![image](https://user-images.githubusercontent.com/8148679/118400988-5baa8080-b67d-11eb-9841-24bc5aba2c12.png)
