### ISSUE TITLE
Server Crash - ModelBiped doesn't exist on server

### ISSUE THREAD

**Issue by MoreThanHidden** [Rumaruka/Industrial-Magic---Crossover#2]
**Version:**
EMT-B_EMT3.4.jar  

**Crash Log:**
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Electro-Magic Tools (emt)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
	at com.rumaruka.emt.init.EMTItems.init(EMTItems.java:93)
	at com.rumaruka.emt.emt.preInit(emt.java:76)
```

**Please add @SideOnly(Side.CLIENT) here:**
https://github.com/Rumaruka/Industrial-Magic---Crossover/blob/eed599f245b6dfe5d2d0facf411b226b665eb68a/java/com/rumaruka/emt/item/armor/ItemInfusedQuantumChestplate.java#L99
**and here:**
https://github.com/Rumaruka/Industrial-Magic---Crossover/blob/eed599f245b6dfe5d2d0facf411b226b665eb68a/java/com/rumaruka/emt/item/armor/ItemFeatherWing.java#L40

**Comment by Rumaruka** [comment]
I don't update this add-on, because work on another project. Sorry

**Comment by Rumaruka** [comment]
Maybe later , but now - no, I don't work

**Comment by MoreThanHidden** [comment]
yeah no worries, might do a PR if I get the time.
