### ISSUE TITLE
(12.4.0) Jump height greatly increased

### ISSUE THREAD

**Issue by ShadowFlame365** [Rumaruka/Industrial-Magic---Crossover#20]
When updated to 12.4.0, normal jumping height is greatly increased for seemingly no reason, about the same height as jumping on a slime block. However, rolling back to 12.3.5 fixes the issue and returns it to normal jumping height.

I attached a short video of each version for reference, recorded at spawn on a newly generated world.

https://user-images.githubusercontent.com/5157049/118914863-f7e0bb80-b8f9-11eb-893e-291cb041de9c.mp4

https://user-images.githubusercontent.com/5157049/118914866-fb744280-b8f9-11eb-938e-4122304cbf7d.mp4

**Comment by Rumaruka** [comment]
Oooops!
Fixed =)

**Comment by Rumaruka** [comment]
Fix in version 12.4.1
