### ISSUE TITLE
Errors with compressed solars

### ISSUE THREAD

**Issue by xJon** [Rumaruka/Industrial-Magic---Crossover#22]
Log: https://mclo.gs/RCj7xst
Thanks :)

**Comment by Rumaruka** [comment]
Maybe you must "play" with version IC2
I dont have time to update my TC addons and Im wait for new TC7 (or TC8, i don`t know)

**Comment by xJon** [comment]
I don't understand what you mean by version IC2? This is for regarding TC6, but nevertheless that's perfectly fine :)

**Comment by Rumaruka** [comment]
UPDATE: Okay, I'm catching bug, will try to fix the holiday
I mean try another version IC2

**Comment by xJon** [comment]
I'm using the latest version of IC2 Experimental, which is the type that work with your addon, I believe

**Comment by Rumaruka** [comment]
Okay, I will try fix this
But don`t sure about the time.
Thanks

**Comment by xJon** [comment]
No worries, whenever you get to it! Thank you :)

**Comment by Rumaruka** [comment]
Fixed
Soon new version

**Comment by xJon** [comment]
Thank you :)
