### ISSUE TITLE
All critical attacks broken when wearing any chestplate

### ISSUE THREAD

**Issue by xJon** [Rumaruka/Industrial-Magic---Crossover#24]
First reported over https://github.com/xJon/The-1.12.2-Pack/issues/824.
When this mod is installed, and the player is wearing any chestplate, one cannot have a critical attack. Easy to demonstrate using the [Target Dummy mod](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm/files/all?filter-game-version=2020709689%3A6756). When this mod is removed the issue is no longer present.
Any idea what's causing this?

**Comment by Rumaruka** [comment]
I don`t know
Im check if i have time and rewrite mods

**Comment by xJon** [comment]
Okay, thank you!
If you have any idea what's modifying critical attacks / chestplates, I could also ask for other help to check it out, as this mod is MIT :)

**Comment by Rumaruka** [comment]
Fixed 
Soon update
