### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [Rumaruka/Industrial-Magic---Crossover#4]
# Heyo! # 
How are you doing today? Love this mod. But I do have a favor to ask of you about it. Would it be possible to also make it compatible with TechReborn? My mod-pack I am building uses TR instead of IC2 and I really would love to have this in it. This would be so I can run this without IC2 being installed. Thanks for considering this request. 

## Cheers! ##

**Comment by Rumaruka** [comment]
this mod oriented only IC2, but I will thinked about it!

**Comment by bigenergy** [comment]
nice idea, +1

**Comment by Rumaruka** [comment]
I make new addon - crossover TechReborn and Thaumcraft 6

**Comment by bookerthegeek** [comment]
> TechReborn and Thaumcraft 6

I look forward to it. :)

**Comment by Rumaruka** [comment]
![image](https://user-images.githubusercontent.com/8148679/53904206-55fd8d00-4067-11e9-87f2-2dd04a22cefb.png)

**Comment by Rumaruka** [comment]
@bookerthegeek and @bigenergy 
![image](https://user-images.githubusercontent.com/8148679/53913114-5b190700-407c-11e9-9c72-59ef0465b54c.png)
