### ISSUE TITLE
HelpFixer

### ISSUE THREAD

**Issue by JohnsBack** [Rumaruka/Industrial-Magic---Crossover#6]
Added HelpFixer mod and now im getting an issue from this not really sure why. If I remove either mod there is no issue.

**Comment by Rumaruka** [comment]
What ? :/

**Comment by JohnsBack** [comment]
So to be upfront I almost have no clue what i'm doing. I just know that there is some sort of conflict between this Mod and the HelpFix mod. I was wondering if there was anything I may be able to do other than the odvious lol.

**Comment by Rumaruka** [comment]
I do not understand what kind of error it is with this mod!

**Comment by JohnsBack** [comment]
Nvm, thanks though.
