### ISSUE TITLE
Баг с квантовыми ботинками путешественника

### ISSUE THREAD

**Issue by bigenergy** [Rumaruka/Industrial-Magic---Crossover#9]
Когда мы снимаем квантовые ботинки путешественника, у них остаётся какое-то ускорение (визуальное), и когда мы начинаем бегать (без ботинок) сервер не понимает что происходит, и сервер кикает игрока с фатальной ошибкой.

**Comment by bigenergy** [comment]
@Rumaruka фикс то ждать?

**Comment by Rumaruka** [comment]
Я еще ничего не восстановил, у меня других проблем полно сейчас, на этот мод в данный момент у меня не доходят руки

**Comment by Rumaruka** [comment]
Проверил, вроде смог синхронизировать!
